### ISSUE TITLE
Ошибка в правилах игры

### ISSUE THREAD

**Issue by osov** [Kicshikxo/Python-checkers#1]
Привет, нашел ошибку что правила игры нарушаются вот на таком примере, можно ли это как-то легко исправить ?
![photo_2022-10-21_11-19-28](https://user-images.githubusercontent.com/38345012/197130166-e091acfe-2657-4dd7-b54b-e5b10f8d3332.jpg)

**Comment by Kicshikxo** [comment]
А в чём заключается нарушение правил? Я толком не нашёл информации по поводу того может ли дамка ходить назад, если там есть ещё одна шашка которую можно съесть.

Я вроде как нашёл таблицу, в которой указано может ли дамка бить назад:
![mozhno-li-bit-nazad-v-shashkah](https://user-images.githubusercontent.com/41877938/197150244-6dcbaa34-d22d-4b96-b0f0-4ac2af7e6067.png)
Так что можно предположить что у меня Русские шашки, в которых такое поведение разрешено

**Comment by osov** [comment]
а вот здесь в правилах:
https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B5_%D1%88%D0%B0%D1%88%D0%BA%D0%B8
параграф **Правила взятия** звучит так:
При взятии применяется правило [турецкого удара](https://ru.wikipedia.org/wiki/%D0%A2%D1%83%D1%80%D0%B5%D1%86%D0%BA%D0%B8%D0%B9_%D1%83%D0%B4%D0%B0%D1%80) — за один ход шашку противника можно побить только один раз. То есть, если при бое нескольких шашек противника шашка или дамка повторно выходит на уже побитую шашку, то ход останавливается.

**Comment by Kicshikxo** [comment]
Понял. Тогда скажу что это легко не исправить, ибо после каждого хода состояние доски полностью обновляется и понять какие шашки были уничтожены в прошлых ходах в данной реализации невозможно.
Я писал эти шашки без ссылки на какие-то правила, поэтому они получились такими какие есть, и я навряд ли буду в них что-либо менять.
